quarkus.application.name=investment-manager

quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:investment_manager}

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

quarkus.default-locale=en-US
quarkus.locales=en-US,pt-BR

quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.orm.jdbc.bind".level=TRACE
quarkus.log.category."org.hibernate.orm.jdbc.bind".min-level=TRACE

# OIDC / Keycloak
quarkus.oidc.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8180/realms/master-wallet}
quarkus.oidc.client-id=${KEYCLOAK_CLIENT_ID:investment-manager-api}
quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET:change-me}
quarkus.oidc.application-type=service
quarkus.oidc.token.principal-claim=sub

# Authorization rules
quarkus.http.auth.permission.register.paths=/api/v1/auth/register
quarkus.http.auth.permission.register.policy=permit
quarkus.http.auth.permission.register.methods=POST

quarkus.http.auth.permission.authenticated.paths=/api/v1/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# Keycloak admin integration
app.keycloak.admin.server-url=${KEYCLOAK_SERVER_URL:http://localhost:8180}
app.keycloak.admin.realm=${KEYCLOAK_REALM:master-wallet}
app.keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:investment-manager-admin}
app.keycloak.admin.client-secret=${KEYCLOAK_ADMIN_CLIENT_SECRET:change-me-admin}

# Current user resolution
app.security.current-user.header-fallback-enabled=false
%dev.app.security.current-user.header-fallback-enabled=true