quarkus.application.name=investment-manager

quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:investment_manager}

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

quarkus.default-locale=en-US
quarkus.locales=en-US,pt-BR

quarkus.log.category."org.hibernate.SQL".level=DEBUG
quarkus.log.category."org.hibernate.orm.jdbc.bind".level=TRACE
quarkus.log.category."org.hibernate.orm.jdbc.bind".min-level=TRACE

# OIDC / Keycloak
quarkus.oidc.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8180/realms/master-wallet}
quarkus.oidc.client-id=${KEYCLOAK_CLIENT_ID:investment-manager-api}
quarkus.oidc.credentials.secret=${KEYCLOAK_CLIENT_SECRET:change-me}
quarkus.oidc.tls.verification=none
quarkus.oidc.application-type=service
quarkus.oidc.authentication.user-info-required=false

# current user resolution
app.security.current-user.claim=user_id
app.security.current-user.subject-claim=sub
app.security.current-user.header-fallback-enabled=false

%dev.app.security.current-user.header-fallback-enabled=true
%dev.quarkus.oidc.enabled=true