CREATE TABLE institutions
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT       NOT NULL REFERENCES users (id),
    name             VARCHAR(150) NOT NULL,
    institution_type VARCHAR(30)  NOT NULL,
    notes            TEXT,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_institutions_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT chk_institutions_type CHECK (institution_type IN ('BANK', 'BROKER', 'OTHER'))
);

CREATE INDEX idx_institutions_user_id ON institutions (user_id);
CREATE UNIQUE INDEX uq_institutions_user_name ON institutions (user_id, name);