CREATE TABLE assets
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT       NOT NULL REFERENCES users (id),
    asset_type    VARCHAR(30)  NOT NULL,
    name          VARCHAR(200) NOT NULL,
    ticker        VARCHAR(30),
    country       VARCHAR(2),
    currency      VARCHAR(3)   NOT NULL,
    issuer        VARCHAR(150),
    metadata_json JSONB,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_assets_type CHECK (
        asset_type IN ('CDB', 'TREASURY_BOND', 'STOCK_BR', 'FII')
        ),
    CONSTRAINT chk_assets_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT chk_assets_ticker_not_blank CHECK (ticker IS NULL OR btrim(ticker) <> ''),
    CONSTRAINT chk_assets_country_format CHECK (
        country IS NULL OR (char_length(country) = 2 AND country = upper(country))
        ),
    CONSTRAINT chk_assets_currency_format CHECK (
        char_length(currency) = 3 AND currency = upper(currency)
        ),
    CONSTRAINT chk_assets_issuer_not_blank CHECK (issuer IS NULL OR btrim(issuer) <> '')
);

CREATE INDEX idx_assets_user_id ON assets (user_id);
CREATE INDEX idx_assets_type ON assets (asset_type);
CREATE UNIQUE INDEX uq_assets_user_asset_type_ticker
    ON assets (user_id, asset_type, ticker) WHERE ticker IS NOT NULL;