CREATE TABLE imported_operation_drafts
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id           BIGINT      NOT NULL REFERENCES import_batches (id),
    imported_file_id   BIGINT      NOT NULL REFERENCES imported_files (id),
    user_id            BIGINT      NOT NULL REFERENCES users (id),
    account_id         BIGINT REFERENCES investment_accounts (id),
    asset_id           BIGINT REFERENCES assets (id),
    raw_asset_name     VARCHAR(255),
    raw_operation_type VARCHAR(50),
    operation_date     TIMESTAMPTZ,
    quantity           NUMERIC(19, 8),
    unit_price         NUMERIC(19, 8),
    gross_amount       NUMERIC(19, 8),
    fees_amount        NUMERIC(19, 8),
    currency           VARCHAR(3),
    status             VARCHAR(30) NOT NULL,
    validation_errors  JSONB,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_imported_operation_drafts_raw_asset_name_not_blank CHECK (
        raw_asset_name IS NULL OR btrim(raw_asset_name) <> ''
        ),
    CONSTRAINT chk_imported_operation_drafts_raw_operation_type_not_blank CHECK (
        raw_operation_type IS NULL OR btrim(raw_operation_type) <> ''
        ),
    CONSTRAINT chk_imported_operation_drafts_currency_format CHECK (
        currency IS NULL OR (char_length(currency) = 3 AND currency = upper(currency))
        ),
    CONSTRAINT chk_imported_operation_drafts_status CHECK (
        status IN ('PENDING_REVIEW', 'VALID', 'INVALID', 'CONFIRMED', 'DISCARDED')
        ),
    CONSTRAINT chk_imported_operation_drafts_quantity_non_negative CHECK (
        quantity IS NULL OR quantity >= 0
        ),
    CONSTRAINT chk_imported_operation_drafts_unit_price_non_negative CHECK (
        unit_price IS NULL OR unit_price >= 0
        ),
    CONSTRAINT chk_imported_operation_drafts_gross_amount_non_negative CHECK (
        gross_amount IS NULL OR gross_amount >= 0
        ),
    CONSTRAINT chk_imported_operation_drafts_fees_amount_non_negative CHECK (
        fees_amount IS NULL OR fees_amount >= 0
        )
);

CREATE INDEX idx_imported_operation_drafts_batch_id ON imported_operation_drafts (batch_id);
CREATE INDEX idx_imported_operation_drafts_imported_file_id ON imported_operation_drafts (imported_file_id);
CREATE INDEX idx_imported_operation_drafts_user_id ON imported_operation_drafts (user_id);
CREATE INDEX idx_imported_operation_drafts_status ON imported_operation_drafts (status);